---
- name: 'Add keys to all owned ssh caches'
  hosts: 'localhost'
  connection: 'local'
  run_once: yes
  vars:
    wisp_full_path: '/dev/shm/wisp.bash'
  vars_files:
    - 'vaults/keys.yml'
  gather_facts: no
  tasks:

    # Get the keys into all correctly owned ssh agents
    - name: 'Find all agents owned by this user'
      register: 'sshAuthSock'
      become: no
      find:
        file_type: 'any'
        paths: '/tmp'
        patterns: 'agent.*'
        recurse: yes

    # TO DO: if no results, run ssh-agent and use that value in nest 0

    # Default to user 'nobody' as this will find no agents and default
    # to no-op, rather than silently run with '' and do who knows what
    - name: 'Load keys into agents'
      with_nested:
        - '{{ sshAuthSock.files | selectattr("pw_name", "eq", lookup("env", "USER") | default("nobody")) }}'
        - '{{ keys }}'
      include_tasks: 'block_load_keys.yml'
...
